name: Auto Pull Request

on:
  workflow_run:
    workflows: ["test"]
    branches: [dev]
    types:
      - completed

jobs:
  auto_pull_request:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        commit-message: 'Auto generate pull request'
        title: 'Auto generate pull request'
        branch: 'main'
        base: 'dev'
